name: release-artifacts

on:
  push:
    tags: ['v*']

jobs:
  release-artifacts:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Build
      run: cd tools/mc2bq && ./aux/build-all.sh

    - name: Release Artifacts
      run: |
        set -x
        cd tools/mc2bq && ./aux/release-artifacts.sh
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
